(self.webpackChunkreact_components=self.webpackChunkreact_components||[]).push([[461],{42938:function(c,d,t){"use strict";t.r(d),t.d(d,{demos:function(){return E}});var h=t(90228),a=t.n(h),l=t(87999),e=t.n(l),s=t(75271),f=t(48691),_=t(15883),E={"button-demo-0":{component:s.memo(s.lazy(e()(a()().mark(function y(){var P,O;return a()().wrap(function(m){for(;;)switch(m.prev=m.next){case 0:return m.next=2,Promise.resolve().then(t.bind(t,15883));case 2:return P=m.sent,O=P.Button,m.abrupt("return",{default:function(){return s.createElement(O,{type:"danger",ghost:!0,size:"small",throttle:3,onClick:function(){console.log(111)}},"test")}});case 5:case"end":return m.stop()}},y)})))),asset:{type:"BLOCK",id:"button-demo-0",refAtomIds:["Button"],dependencies:{"index.jsx":{type:"FILE",value:`import { Button } from 'react-components';

export default () => (
  <Button
    type="danger"
    ghost
    // shape="circle"
    size="small"
    // disabled
    // icon={<div>icon</div>}
    // debounce={3}
    throttle={3}
    onClick={() => {
      console.log(111);
    }}
  >
    test
  </Button>
);`},"react-components":{type:"NPM",value:"0.0.1"}},entry:"index.jsx"},context:{"react-components":_},renderOpts:{compile:function(){var y=e()(a()().mark(function O(){var x,m=arguments;return a()().wrap(function(p){for(;;)switch(p.prev=p.next){case 0:return p.next=2,t.e(19).then(t.bind(t,54019));case 2:return p.abrupt("return",(x=p.sent).default.apply(x,m));case 3:case"end":return p.stop()}},O)}));function P(){return y.apply(this,arguments)}return P}()}}}},15883:function(c,d,t){"use strict";t.r(d),t.d(d,{Button:function(){return z}});var h=t(26068),a=t.n(h),l=t(82092),e=t.n(l),s=t(48305),f=t.n(s),_=t(67825),E=t.n(_),y=t(75271),P="yx-",O=function(o){return"".concat(P).concat(o)};function x(n){var o,u,r="";if(typeof n=="string"||typeof n=="number")r+=n;else if(typeof n=="object")if(Array.isArray(n)){var j=n.length;for(o=0;o<j;o++)n[o]&&(u=x(n[o]))&&(r&&(r+=" "),r+=u)}else for(u in n)n[u]&&(r&&(r+=" "),r+=u);return r}function m(){for(var n,o,u=0,r="",j=arguments.length;u<j;u++)(n=arguments[u])&&(o=x(n))&&(r&&(r+=" "),r+=o);return r}var T=m,p=t(52676),U=["type","size","ghost","shape","children","disabled","icon","debounce","throttle","onClick"],C=O("btn");function z(n){var o=n.type,u=n.size,r=n.ghost,j=r===void 0?!1:r,W=n.shape,$=n.children,F=n.disabled,G=n.icon,D=n.debounce,b=n.throttle,i=n.onClick,N=E()(n,U),H=(0,y.useState)(F),L=f()(H,2),M=L[0],I=L[1],v=(0,y.useRef)(),J=(0,y.useState)(0),R=f()(J,2),A=R[0],S=R[1],Q=function(g){v!=null&&v.current&&clearTimeout(v==null?void 0:v.current),v.current=setTimeout(function(){M||i&&(i==null||i(g))},D?typeof D=="boolean"?1e3:D*1e3:0)},V=function(g){var B=b?typeof b=="boolean"?1:b:0;S(B),I(!0),v.current=setInterval(function(){B>0&&(M||I(!0),B=B-1,S(B)),B<=0&&(i&&(i==null||i(g)),I(!1),clearInterval(v.current))},1e3)};return(0,p.jsxs)("button",a()(a()({},N),{},{className:T(C,e()(e()(e()(e()(e()({},"".concat(C,"-").concat(o),o),"".concat(C,"-").concat(u),u),"".concat(C,"-").concat(o,"-ghost"),j),"".concat(C,"-").concat(o,"-").concat(W),W),"".concat(C,"-").concat(o,"-disabled"),M)),onClick:function(g){D&&Q(g),b&&!M&&V(g),!b&&!D&&i&&(i==null||i(g))},children:[G,b&&A?(0,p.jsxs)("div",{children:[A,"s\u540E\u53EF\u70B9\u51FB"]}):null,b&&A?null:$]}))}},4144:function(c,d,t){"use strict";t.r(d),t.d(d,{texts:function(){return a}});var h=t(48691);const a=[{value:"This is an example component.",paraId:0,tocIndex:0}]},67825:function(c,d,t){var h=t(64382);function a(l,e){if(l==null)return{};var s=h(l,e),f,_;if(Object.getOwnPropertySymbols){var E=Object.getOwnPropertySymbols(l);for(_=0;_<E.length;_++)f=E[_],!(e.indexOf(f)>=0)&&Object.prototype.propertyIsEnumerable.call(l,f)&&(s[f]=l[f])}return s}c.exports=a,c.exports.__esModule=!0,c.exports.default=c.exports},64382:function(c){function d(t,h){if(t==null)return{};var a={},l=Object.keys(t),e,s;for(s=0;s<l.length;s++)e=l[s],!(h.indexOf(e)>=0)&&(a[e]=t[e]);return a}c.exports=d,c.exports.__esModule=!0,c.exports.default=c.exports}}]);
